import { Inter } from "next/font/google";
import "@/styles/globals.css";

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

// This layout takes in everything the page.js file gives
// as childen
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
